kind = "web"
previewPath = "/"
title = "Afro Fish/s"
version = "1.0.0"
id = "artifacts/afro-fish"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 19833

[services.development]
run = "pnpm --filter @workspace/afro-fish run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/afro-fish", "run", "build" ]
publicDir = "artifacts/afro-fish/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "19833"
BASE_PATH = "/"
